### ISSUE TITLE
Event registration / Team creation and join team

### ISSUE THREAD

**Issue by Varun-Kolanu** [codefest-iit-bhu/codefest-frontend#10]
## Backend URLs:
- API Docs and testing playground: https://codefest-backend-igxy.onrender.com/api-docs
- Base backend url for API calls: https://codefest-backend-igxy.onrender.com/api/v1

## Flow:

- User clicks on Register button on /event/:eventName page and then will be asked for team name in a popup. As he types, he'll be shown whether the team name is valid or not (Use `/team/name_available` route here). Apply **Debouncing** here (Learn about debouncing [here](https://www.freecodecamp.org/news/debouncing-explained/)). On success, redirect to /myTeams page

![image](https://github.com/user-attachments/assets/d23c6fcb-7347-4379-9d93-1b60958cc45d)

- Add a Join button in /event page. On clicking this Join button, a popup will be opened which asks for teamCode and then use `/member/join` endpoint to make him join. After successful response, redirect him to /myTeams page.

**Comment by abhigupta0507** [comment]
@codefest-bot claim
