### ISSUE TITLE
My Teams Page

### ISSUE THREAD

**Issue by Varun-Kolanu** [codefest-iit-bhu/codefest-frontend#11]
## Backend Urls:

- API Docs and testing playground: https://codefest-backend-igxy.onrender.com/api-docs
- Base backend url for API calls: https://codefest-backend-igxy.onrender.com/api/v1

## Taks:

- My Teams page consists of all the teams I'm in. Call `/team/myTeams` to get my teams. 
- The endpoint returns teams with the _id, name, code, member details

- User can see all the teams he is in. Each team will be like a card having team name, team code, space remaining (number of members those can join), members’ names, change leader dropdown (only leader can change the leader), delete team option at the top right corner (only leader can do). 
- There will also be an option to exit the team in the card (you can do it only before the deadline). 
- Team leader can delete a team member, so if someone is a team leader show delete option beside the members.

**Comment by dshayon05** [comment]
@codefest-bot claim
