### ISSUE TITLE
CA Registration page

### ISSUE THREAD

**Issue by Varun-Kolanu** [codefest-iit-bhu/codefest-frontend#12]
## Backend Urls:

- API Docs and testing playground: https://codefest-backend-igxy.onrender.com/api-docs
- Base backend url for API calls: https://codefest-backend-igxy.onrender.com/api/v1

## Tasks:

- When a user clicks on register button on register on CA page, a page or popup will be opened to ask user the details like his Institute name and description (like Statement of Purpose).
- He can see his request in the CA page. He can update it. Update from the requestee can only be the status update (say if admin rejected the request and written and admin message, after doing the changes, he can click on button smth like "Done". Then the status changes to pending.)

**Comment by techbro-2k05** [comment]
@codefest-bot claim
