### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by Varun-Kolanu** [codefest-iit-bhu/codefest-frontend#13]
- API Docs and testing playground: https://codefest-backend-igxy.onrender.com/api-docs
- Base backend url for API calls: https://codefest-backend-igxy.onrender.com/api/v1

## Flow:

- Admin can see all the users registered
- Admin can see all the CA requests
- He can see a CA request and click on approve or reject. Also he can update the CA request by sending an adminMessage to be seen by the requestee.

**Comment by Hemant2A2** [comment]
How is the admin user created? I don't see any endpoint for that in the backend. Won't we need a separate login for admins?

**Comment by Hemant2A2** [comment]
@codefest-bot claim

**Comment by Hemant2A2** [comment]
@codefest-bot claim
