### ISSUE TITLE
Integrate Manual auth (Signup and Login) with backend

### ISSUE THREAD

**Issue by Varun-Kolanu** [codefest-iit-bhu/codefest-frontend#8]
## Backend Urls or endpoints:
- API Docs and testing playground: https://codefest-backend-igxy.onrender.com/api-docs
- Base backend url for API calls: https://codefest-backend-igxy.onrender.com/api/v1
- Signup: /auth/signup
- Login: /auth/login
- Verify email: /auth/verify_email

## Flow:

![image](https://github.com/user-attachments/assets/61b4dd6b-18a5-4494-9529-e8c770d3e97f)

![image](https://github.com/user-attachments/assets/ec494261-27d7-4019-a8eb-c28a60c4c1c4)

You'll get refreshToken in response after email Verification. So, save that refreshToken in localStorage to be used later.

**Comment by Hemant2A2** [comment]
@codefest-bot claim

**Comment by Hemant2A2** [comment]
@codefest-bot abandon
