### ISSUE TITLE
Google Oauth Flow

### ISSUE THREAD

**Issue by Varun-Kolanu** [codefest-iit-bhu/codefest-frontend#9]
## Backend Urls or endpoints:
- API Docs and testing playground: https://codefest-backend-igxy.onrender.com/api-docs
- Base backend url for API calls: https://codefest-backend-igxy.onrender.com/api/v1
- Set Password: /auth/set-password

## Flow:

![image](https://github.com/user-attachments/assets/98a372d5-498f-435d-8f7e-019228693a1d)

Just call the endpoint /Oauth2/google then handle setPassword page after redirection
You'll get refreshToken in response after setPassword if new user and after google login if existing user. So, save that refreshToken in localStorage to be used later.

Also implement the logout by seeing the /auth/logout endpoint

**Comment by mridulathya** [comment]
@codefest-bot claim
